import {
  AntennaSignal,
  Attachment,
  Camera,
  CheckCircle,
  ControlSlider,
  CursorPointer,
  DashboardDots,
  DataTransferBoth,
  Drag,
  HdDisplay,
  Headset,
  InfoCircle,
  Microphone,
  MicrophoneMute,
  MicrophoneSpeaking,
  NavArrowDown,
  Plus,
  RefreshDouble,
  SoundHigh,
  WarningCircle,
  Xmark,
  XmarkCircle,
  Trash,
} from "iconoir-react";

export const AppIcons = {
  Activity: SoundHigh,
  Attachment,
  Auto: AntennaSignal,
  Camera,
  Check: CheckCircle,
  Close: Xmark,
  CloseCircle: XmarkCircle,
  Cursor: CursorPointer,
  Dashboard: DashboardDots,
  Drag,
  Info: InfoCircle,
  Loader: RefreshDouble,
  Mic: Microphone,
  MicMuted: MicrophoneMute,
  MicSpeaking: MicrophoneSpeaking,
  Multi: DataTransferBoth,
  New: Plus,
  Screen: HdDisplay,
  Screenshot: Camera,
  Smart: ControlSlider,
  SystemAudio: Headset,
  Trash,
  Warning: WarningCircle,
  ChevronDown: NavArrowDown,
};
