import {
  Attachment,
  Camera,
  CheckCircle,
  CursorPointer,
  DashboardDots,
  Drag,
  HdDisplay,
  InfoCircle,
  MicrophoneMute,
  MicrophoneSpeaking,
  NavArrowDown,
  RefreshDouble,
  WarningCircle,
  Xmark,
  XmarkCircle,
  Trash,
} from "iconoir-react";
import {
  AudioLines,
  AudioWaveform,
  Brain,
  Layers2,
  Mic,
  Plus,
  Sparkles,
} from "lucide-react";

export const AppIcons = {
  Activity: AudioLines,
  Attachment,
  BrainToggle: Brain,
  Auto: AudioLines,
  Camera,
  Check: CheckCircle,
  Close: Xmark,
  CloseCircle: XmarkCircle,
  Cursor: CursorPointer,
  Dashboard: DashboardDots,
  Drag,
  Info: InfoCircle,
  Loader: RefreshDouble,
  Mic,
  MicMuted: MicrophoneMute,
  MicSpeaking: MicrophoneSpeaking,
  Multi: Layers2,
  New: Plus,
  Screen: HdDisplay,
  Screenshot: Camera,
  Smart: Sparkles,
  SystemAudio: AudioWaveform,
  Trash,
  Warning: WarningCircle,
  ChevronDown: NavArrowDown,
};
