import React, { createContext, useContext, useState, useEffect } from "react";
import { getResponseSettings, updateLanguage } from "../lib/storage/response-settings.storage";

export const translations = {
  en: {

    sidebar_dashboard: "Dashboard",
    sidebar_chats: "Chats",
    sidebar_system_prompts: "System prompts",
    sidebar_app_settings: "App Settings",
    sidebar_responses: "Responses",
    sidebar_screenshot: "Screenshot",
    sidebar_audio: "Audio",
    sidebar_shortcuts: "Cursor & Shortcuts",
    sidebar_dev_space: "Dev space",
    sidebar_support: "Contact Support",
    sidebar_bug: "Report a bug",
    sidebar_quit: "Quit invisibleai",
    sidebar_version: "Version",
    sidebar_loading: "Loading...",

    enabled: "Enabled",
    disabled: "Disabled",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    loading: "Loading...",
    success: "Success",
    error: "Error",
    warning: "Warning",
    tip: "Tip",
    active: "Active",
    inactive: "Inactive",

    dashboard_title: "Dashboard",
    dashboard_description: "InvisibleAI license to unlock faster responses, quicker support and premium features.",
    dashboard_get_license: "Get License",
    dashboard_usage_title: "Usage Overview",
    dashboard_usage_desc: "Track your token consumption and active sessions.",

    dev_title: "Dev Space",
    dev_desc: "Manage providers for AI and speech-to-text.",
    dev_contribute_title: "Contribute to InvisibleAI, Earn Lifetime Access",
    dev_contribute_desc: "Fix a listed critical issue and earn a lifetime Dev Pro license valued at $120. Only issues on our contribute page qualify. Read more at invisibleai.com/contribute.",
    dev_ai_title: "AI Providers",
    dev_ai_desc: "Select your AI provider, API key, and model.",
    dev_stt_title: "STT Providers",
    dev_stt_desc: "Select your speech-to-text provider, API key, and model.",
    dev_select_ai_provider: "Select AI Provider",
    dev_select_ai_provider_desc: "Choose the AI service provider used for responses.",
    dev_select_stt_provider: "Select STT Provider",
    dev_select_stt_provider_desc: "Choose the speech-to-text service provider used for transcription.",
    dev_choose_ai_provider: "Choose your AI provider",
    dev_choose_stt_provider: "Choose your STT provider",
    dev_provider_fallback: "Provider",
    dev_api_key: "API Key",
    dev_api_key_desc: "Enter your {provider} API key. It stays local on this device.",
    dev_submit_api_key: "Submit API Key",
    dev_remove_api_key: "Remove API Key",
    dev_model: "Model",
    dev_model_desc: "Add the model name for {provider}.",
    dev_model_placeholder: "Enter model name",
    dev_advanced_title: "Advanced",
    dev_advanced_ai_desc: "Manage custom AI providers in a separate workspace.",
    dev_advanced_stt_desc: "Manage custom speech-to-text providers in a separate workspace.",
    dev_custom_create: "Custom provider",
    dev_custom_edit: "Edit custom provider",
    dev_custom_empty: "No custom providers configured.",
    dev_custom_no_path: "Response path not set",
    dev_custom_ai_dialog_desc: "Configure a custom AI provider using a cURL template.",
    dev_custom_stt_dialog_desc: "Configure a custom STT provider using a cURL template.",
    dev_custom_curl: "cURL command",
    dev_custom_ai_curl_desc: "Use {{TEXT}}, {{SYSTEM_PROMPT}}, {{IMAGE}}, {{API_KEY}}, and {{MODEL}} where needed.",
    dev_custom_stt_curl_desc: "Use {{AUDIO}}, {{API_KEY}}, and {{MODEL}} where needed.",
    dev_custom_streaming: "Streaming",
    dev_custom_streaming_desc: "Enable streaming if the provider supports token streaming.",
    dev_custom_response_path: "Path used to extract text from the provider response.",
    dev_custom_delete_title: "Delete custom provider",
    dev_custom_delete_desc: "This custom provider will be removed from local storage.",
    dev_autofill: "Auto-fill",

    responses_title: "Response Settings",
    responses_desc: "Customize how AI generates and displays responses",
    responses_premium_title: "Premium Features",
    responses_premium_desc: "Response customization features (Response Length, Language Selection, and Auto-Scroll Control) require an active license to use.",

    responses_len_title: "Response Length",
    responses_len_desc: "Control how detailed the AI responses should be. Changes apply to all new conversations and will influence how the AI structures responses",
    responses_len_short_title: "Short",
    responses_len_short_desc: "Best for quick answers, summaries, and when you need to save time",
    responses_len_medium_title: "Medium",
    responses_len_medium_desc: "Balanced responses with adequate explanations for most tasks",
    responses_len_auto_title: "Auto",
    responses_len_auto_desc: "AI determines the best length based on your question's complexity",

    responses_lang_title: "Response Language",
    responses_lang_desc: "Select the language for AI responses. Setting applies globally to all providers and conversations. Language support may vary depending on your selected LLM provider",
    responses_lang_placeholder: "Select a language",

    responses_scroll_title: "Auto-Scroll Behavior",
    responses_scroll_desc: "Control whether responses automatically scroll to the bottom. This setting applies immediately and controls whether responses automatically scroll to the latest content as it streams",
    responses_scroll_enabled: "Auto-Scroll Enabled",
    responses_scroll_disabled: "Auto-Scroll Disabled",
    responses_scroll_enabled_desc: "Responses will automatically scroll to the bottom as they arrive",
    responses_scroll_disabled_desc: "Responses will stay at your current scroll position",

    responses_memory_title: "Conversational Memory",
    responses_memory_desc: "Control whether the AI remembers past discussions to stay context-aware across all chats and audio interactions.",
    responses_memory_enabled: "Conversational Memory Enabled",
    responses_memory_disabled: "Conversational Memory Disabled",
    responses_memory_enabled_desc: "AI will recall details from up to 15 past conversations for global context.",
    responses_memory_disabled_desc: "AI will treat each conversation as a completely clean slate.",

    settings_title: "Settings",
    settings_desc: "Manage your settings",

    settings_theme_title: "Theme Customization",
    settings_theme_desc: "Personalize your experience with custom theme and transparency settings",
    settings_theme_license_warning: " (You need an active license to use this feature)",
    settings_theme_system: "System",
    settings_theme_light: "Light Mode",
    settings_theme_dark: "Dark Mode",
    settings_theme_light_desc: "Using light theme for better visibility in bright environments",
    settings_theme_dark_desc: "Using dark theme for comfortable viewing in low light",
    settings_theme_transparency: "Window Transparency",
    settings_theme_transparency_desc: "Adjust the transparency level of the application window",
    settings_theme_transparency_tip: "Tip: Higher transparency lets you see through the window, perfect for dark overlay. Changes apply immediately.",

    settings_startup_title: "Launch on Startup",
    settings_startup_desc: "Automatically open InvisibleAI when your system starts",
    settings_startup_label: "Open on Start",
    settings_startup_enabled: "InvisibleAI will launch automatically on system startup",
    settings_startup_disabled: "InvisibleAI will not launch automatically",

    settings_icon_title: "App Icon Stealth Mode",
    settings_icon_desc: "Control dock/taskbar icon visibility when window is hidden for maximum discretion",
    settings_icon_show: "Show Icon in Dock/Taskbar",
    settings_icon_hide: "Hide Icon from Dock/Taskbar",
    settings_icon_visible_tip: "Toggle to make App Icon Visible",
    settings_icon_hidden_tip: "Toggle to make App Icon Hidden",

    settings_always_on_top_title: "Always On Top Mode",
    settings_always_on_top_desc: "Control whether the window stays above all other applications",
    settings_always_on_top_enabled: "Disable Always On Top",
    settings_always_on_top_disabled: "Enable Always On Top",
    settings_always_on_top_enabled_desc: "Window stays above all other applications (default)",
    settings_always_on_top_disabled_desc: "Window behaves like normal applications",

    settings_stealth_title: "Stealth Mode (Invisible to Screenshots)",
    settings_stealth_desc: "When enabled, the app becomes invisible to screen recordings and screenshots. Requires an active license.",

    settings_reset_title: "Reset App Configuration",
    settings_reset_desc: "Reset InvisibleAI to its factory defaults. This will delete ALL data including chat history, API keys, license, system prompts, audio settings, and all preferences. The app will restart automatically.",
    settings_reset_warning: "This action is irreversible. All your configuration, API keys, license, and chat history will be permanently deleted.",
    settings_reset_button: "Reset App to Factory Defaults",
    settings_reset_button_loading: "Resetting...",
    settings_reset_dialog_title: "Reset All App Data?",
    settings_reset_dialog_desc: "This will permanently delete:",
    settings_reset_dialog_items: "All chat conversations and history;API keys;InvisibleAI license and credentials;System prompts and preferences;Audio and screenshot settings;Theme and display settings;All other app configuration",
    settings_reset_dialog_warn: "The app will restart after reset. This cannot be undone.",
    settings_reset_dialog_cancel: "Cancel",
    settings_reset_dialog_confirm: "Reset Everything",

    settings_language_title: "App Language",
    settings_language_desc: "Choose the display language for the entire application interface",
    settings_language_spanish: "Español",
    settings_language_english: "English",
    settings_language_current: "Current language",
    settings_language_active: "Active",

    api_setup_select_pro: "Select pro models",
    api_setup_license_key: "License Key",
    api_setup_license_key_desc: "After completing your purchase, you'll receive a license key via email. Paste it below to activate.",
    api_setup_license_key_placeholder: "Enter your license key (e.g., 38b1460a-5104-4067-a91d-77b872934d51)",
    api_setup_current_license: "Current License",
    api_setup_activate: "Activate License",
    api_setup_remove: "Remove License",
    api_setup_support_info: "If you need any help or any assistance, contact support@invisibleai.com",
    api_setup_enable_api: "Enable InvisibleAI API",
    api_setup_disable_api: "Disable InvisibleAI API",
    api_setup_api_enabled_desc: "Using all invisibleai APIs for audio, and chat.",
    api_setup_api_disabled_desc: "Using all your own AI Providers for audio, and chat.",
    api_setup_api_no_license_desc: "A valid license is required to enable InvisibleAI API or you can use your own AI Providers and STT Providers.",

    audio_title: "Audio Settings",
    audio_desc: "Configure your audio input and output devices for voice interaction and system audio capture.",
    audio_mic_label: "Microphone",
    audio_mic_desc: "Select your microphone for voice input and speech-to-text. If issues occur, adjust your system's default microphone in OS settings.",
    audio_mic_loading: "Loading microphones...",
    audio_mic_none: "No microphones found",
    audio_mic_placeholder: "Select a microphone",
    audio_mic_success: "Microphone changed successfully.",
    audio_mic_refresh_tip: "Click the refresh button to load your microphone devices. If this doesn't work, try changing your default microphone in your system settings.",
    audio_mic_tip: "Tip: When you select a microphone, the app will switch to that device immediately. You can verify this by hovering over the microphone button in the main interface - it will show the active device name.",
    audio_sys_title: "System Audio",
    audio_sys_desc: "Select the output device to capture system sounds and application audio. If issues occur, set the correct default output in OS settings.",
    audio_sys_loading: "Loading output devices...",
    audio_sys_none: "No output devices found",
    audio_sys_placeholder: "Select an output device",
    audio_sys_success: "Output device changed successfully.",
    audio_sys_refresh_tip: "Click the refresh button to load your system audio devices. If this doesn't work, try changing your default system audio output in your system settings.",
    audio_sys_tip: "Tip: System audio capture allows you to record audio playing through your speakers or headphones. This is useful for capturing conversation audio or system sounds along with your voice.",
    audio_trouble_title: "If selected devices don't work:",
    audio_trouble_desc: "Please verify your default system audio settings. Go to {mic} for microphone and {audio} for speakers/headphones. Ensure the correct devices are set as default in your operating system.",
    audio_trouble_note: "Note: If the selected device fails or is unavailable, InvisibleAI will automatically fall back to your system's default audio devices.",
    audio_default_suffix: " (Default)",
    audio_refresh_mic_title: "Refresh microphone list",
    audio_refresh_sys_title: "Refresh output device list",
    audio_using_prefix: "Using: ",

    screenshot_title: "Screenshot",
    screenshot_desc: "Manage your screenshot settings",
    screenshot_method_title: "Capture Method",
    screenshot_method_screenshot_desc: "Screenshot Mode: Quickly capture the entire screen with one click.",
    screenshot_method_selection_desc: "Selection Mode: Click and drag to select a specific area to capture.",
    screenshot_method_screenshot_mode: "Screenshot Mode",
    screenshot_method_selection_mode: "Selection Mode",
    screenshot_method_license_required: "You need an active license to use Selection Mode.",
    screenshot_proc_title: "Processing Mode",
    screenshot_proc_manual_desc: "Screenshots will be captured and automatically added to your attached files. You can then submit them with your own prompt. you can capture multiple screenshots and submit them later.",
    screenshot_proc_auto_desc: "Screenshots will be automatically submitted to AI using your custom prompt. No manual intervention required. only one screenshot can be submitted at a time.",
    screenshot_proc_auto_mode: "Auto Mode",
    screenshot_proc_manual_mode: "Manual Mode",
    screenshot_auto_prompt_label: "Auto Prompt",
    screenshot_auto_prompt_placeholder: "Enter prompt for automatic screenshot analysis...",
    screenshot_auto_prompt_help: "This prompt will be used automatically when screenshots are taken",
    screenshot_tip: "Tip: Auto mode is great for quick analysis, manual mode gives you more control.",

    shortcuts_title: "Cursor & Keyboard Shortcuts",
    shortcuts_desc: "Manage your cursor and keyboard shortcuts",
    shortcuts_cursor_title: "Cursor",
    shortcuts_cursor_desc: "Control invisibleai cursor visibility",
    shortcuts_cursor_placeholder: "Select a cursor type",
    shortcuts_cursor_invisible: "Invisible",
    shortcuts_cursor_default: "Default",
    shortcuts_cursor_auto: "Auto",
    shortcuts_cursor_linux_not_supported: "Not supported on Linux",
    shortcuts_kb_title: "Keyboard Shortcuts",
    shortcuts_kb_configured: "configured",
    shortcuts_kb_license_warning: " • Get a license to customize shortcuts",
    shortcuts_kb_reset_title: "Reset all shortcuts to platform defaults",
    shortcuts_kb_reset_btn: "Reset",
    shortcuts_kb_unlock_title: "Unlock Shortcut Customization",
    shortcuts_kb_unlock_desc: "You can enable/disable shortcuts, but need a active license to customize the key bindings.",
    shortcuts_kb_change_btn: "Change",
    shortcuts_kb_change_btn_title: "Change this shortcut",
    shortcuts_kb_locked_btn_title: "License required to customize",
    shortcuts_kb_footer: "Shortcuts work globally, even when the app is hidden",

    recorder_waiting: "Waiting for keys...",
    recorder_save: "Save",
    recorder_save_title: "Save shortcut",
    recorder_cancel: "Cancel",
    recorder_cancel_title: "Cancel",
    recorder_err_arrow: "Arrow keys are automatic for Move Window. Only set modifiers.",
    recorder_err_modifier: "Must include at least one modifier (Cmd/Ctrl/Alt/Shift)",
    recorder_err_modifier_key: "Must include at least one modifier (Cmd/Ctrl/Alt/Shift) and one key",
    recorder_err_move_modifier: "Move Window needs at least one modifier",
    recorder_err_shortcut_modifier: "Shortcut must have at least one modifier and one key",
    recorder_err_invalid: "Invalid shortcut combination",
    recorder_err_not_supported: "This shortcut combination is not supported",
    recorder_err_failed: "Failed to validate shortcut",
    recorder_help_move: "Press modifier keys (e.g., Cmd+Shift). Arrow keys work automatically.",
    recorder_help_shortcut: "Press a key combination now (e.g., Cmd+Shift+K)",
    recorder_captured: "Shortcut captured. Click 'Save' to apply.",

    prompts_title: "System Prompts",
    prompts_desc: "Manage your AI behavior profiles and create new ones",
    prompts_search_placeholder: "Search system prompts...",
    prompts_create_btn: "Create New",
    prompts_none_title: "No prompts found",
    prompts_none_desc: "Create a new prompt to get started",
    prompts_edit: "Edit",
    prompts_delete: "Delete",
    prompts_default_title: "InvisibleAI Default Prompts",
    prompts_default_desc: "Pre-configured prompts with optimal model pairings. Selecting a prompt will automatically set the recommended AI model for best results.",
    prompts_default_loading_title: "Loading prompts...",
    prompts_default_loading_desc: "Fetching InvisibleAI default prompts",
    prompts_last_updated: "Last updated: ",
    prompts_unlock_btn: "Unlock",
    prompts_delete_title: "Delete System Prompt",
    prompts_delete_confirm: "Are you sure you want to delete \"{name}\"?",
    prompts_delete_warning: "This action cannot be undone. This will permanently delete the system prompt from the database.",
    prompts_deleting: "Deleting...",
    prompts_create_title: "Create System Prompt",
    prompts_edit_title: "Edit System Prompt",
    prompts_create_desc: "Define a new AI behavior and personality.",
    prompts_edit_desc: "Update your system prompt details below.",
    prompts_label_name: "Name",
    prompts_placeholder_name: "e.g., Code Review Expert, Creative Writer...",
    prompts_label_prompt: "System Prompt",
    prompts_placeholder_prompt: "You are a helpful AI assistant. Be concise, accurate, and friendly in your responses...",
    prompts_tip_prompt: "Tip: Be specific about tone, expertise level, and response format",
    prompts_updating: "Updating...",
    prompts_creating: "Creating...",
    prompts_update_btn: "Update",
    prompts_create_btn_save: "Create",
    prompts_generate_with_ai: "Generate with AI",
    prompts_generate_title: "Generate a system prompt",
    prompts_generate_desc: "Describe the AI behavior you want, and we'll generate a prompt for you.",
    prompts_generate_placeholder: "e.g., I want an AI that helps me with code reviews and focuses on best practices...",
    prompts_generate_error_empty: "Please describe what you want",
    prompts_generate_error_fail: "Failed to generate prompt",
    prompts_generating: "Generating...",
    prompts_generate_btn: "Generate",
    prompts_license_required: "You need an active license to use this feature. Click the button below to get a license.",

    chats_title: "All conversations",
    chats_desc: "View all your conversations",
    chats_none_title: "No conversations found",
    chats_none_desc: "Start a new conversation to get started",
    chats_search_placeholder: "Search conversations...",
    chats_messages_count: "messages",

    chat_ask_placeholder: "Ask me anything...",
    chat_mode_conversation: "Conversation Mode",
    chat_mode_ai_response: "AI Response",
    chat_scroll_hint: "(Use arrow keys to scroll)",
    chat_toggle_prefix: "Toggle ",
    chat_error_prefix: "Error:",
    chat_generating: "Generating response...",
    chat_role_user: "You",
    chat_role_ai: "AI",
    chat_cancel_title: "Cancel loading",
    chat_close_new_title: "Close and start new conversation",
    chat_clear_title: "Clear conversation",
  },
  es: {

    sidebar_dashboard: "Panel",
    sidebar_chats: "Chats",
    sidebar_system_prompts: "Prompts del sistema",
    sidebar_app_settings: "Ajustes",
    sidebar_responses: "Respuestas",
    sidebar_screenshot: "Captura de pantalla",
    sidebar_audio: "Audio",
    sidebar_shortcuts: "Cursor y Accesos directos",
    sidebar_dev_space: "Espacio de desarrollo",
    sidebar_support: "Soporte de contacto",
    sidebar_bug: "Reportar un error",
    sidebar_quit: "Salir de InvisibleAI",
    sidebar_version: "Versión",
    sidebar_loading: "Cargando...",

    enabled: "Activado",
    disabled: "Desactivado",
    cancel: "Cancelar",
    save: "Guardar",
    delete: "Eliminar",
    loading: "Cargando...",
    success: "Éxito",
    error: "Error",
    warning: "Advertencia",
    tip: "Consejo",
    active: "Activo",
    inactive: "Inactivo",

    dashboard_title: "Panel de control",
    dashboard_description: "Licencia InvisibleAI para desbloquear respuestas más rápidas, soporte ágil y funciones premium.",
    dashboard_get_license: "Obtener Licencia",
    dashboard_usage_title: "Resumen de Uso",
    dashboard_usage_desc: "Seguimiento de consumo de tokens y sesiones activas.",

    dev_title: "Espacio de desarrollo",
    dev_desc: "Gestiona proveedores de IA y transcripción.",
    dev_contribute_title: "Contribuye a InvisibleAI y gana acceso de por vida",
    dev_contribute_desc: "Corrige un problema crítico listado y gana una licencia Dev Pro de por vida valorada en $120. Solo califican los issues de nuestra página de contribución. Lee más en invisibleai.com/contribute.",
    dev_ai_title: "Proveedores de IA",
    dev_ai_desc: "Selecciona proveedor de IA, API key y modelo.",
    dev_stt_title: "Proveedores STT",
    dev_stt_desc: "Selecciona proveedor de transcripción, API key y modelo.",
    dev_select_ai_provider: "Seleccionar proveedor de IA",
    dev_select_ai_provider_desc: "Elige el proveedor de IA usado para las respuestas.",
    dev_select_stt_provider: "Seleccionar proveedor STT",
    dev_select_stt_provider_desc: "Elige el proveedor de transcripción usado para convertir audio a texto.",
    dev_choose_ai_provider: "Elige tu proveedor de IA",
    dev_choose_stt_provider: "Elige tu proveedor STT",
    dev_provider_fallback: "Proveedor",
    dev_api_key: "API Key",
    dev_api_key_desc: "Ingresa tu API key de {provider}. Se guarda localmente en este dispositivo.",
    dev_submit_api_key: "Guardar API Key",
    dev_remove_api_key: "Quitar API Key",
    dev_model: "Modelo",
    dev_model_desc: "Agrega el nombre del modelo para {provider}.",
    dev_model_placeholder: "Ingresa el nombre del modelo",
    dev_advanced_title: "Avanzado",
    dev_advanced_ai_desc: "Gestiona proveedores de IA personalizados en un espacio separado.",
    dev_advanced_stt_desc: "Gestiona proveedores STT personalizados en un espacio separado.",
    dev_custom_create: "Proveedor personalizado",
    dev_custom_edit: "Editar proveedor personalizado",
    dev_custom_empty: "No hay proveedores personalizados configurados.",
    dev_custom_no_path: "Ruta de respuesta sin configurar",
    dev_custom_ai_dialog_desc: "Configura un proveedor de IA personalizado usando una plantilla cURL.",
    dev_custom_stt_dialog_desc: "Configura un proveedor STT personalizado usando una plantilla cURL.",
    dev_custom_curl: "Comando cURL",
    dev_custom_ai_curl_desc: "Usa {{TEXT}}, {{SYSTEM_PROMPT}}, {{IMAGE}}, {{API_KEY}} y {{MODEL}} cuando sea necesario.",
    dev_custom_stt_curl_desc: "Usa {{AUDIO}}, {{API_KEY}} y {{MODEL}} cuando sea necesario.",
    dev_custom_streaming: "Streaming",
    dev_custom_streaming_desc: "Activa streaming si el proveedor soporta transmisión de tokens.",
    dev_custom_response_path: "Ruta usada para extraer el texto de la respuesta del proveedor.",
    dev_custom_delete_title: "Eliminar proveedor personalizado",
    dev_custom_delete_desc: "Este proveedor personalizado se eliminará del almacenamiento local.",
    dev_autofill: "Autocompletar",

    responses_title: "Ajustes de Respuestas",
    responses_desc: "Personaliza cómo la IA genera y muestra las respuestas",
    responses_premium_title: "Funciones Premium",
    responses_premium_desc: "Las funciones de personalización de respuestas (Longitud de respuesta, Selección de idioma y Control de auto-desplazamiento) requieren una licencia activa para su uso.",

    responses_len_title: "Longitud de Respuesta",
    responses_len_desc: "Controla qué tan detalladas deben ser las respuestas de la IA. Los cambios se aplican a todas las conversaciones nuevas e influirán en cómo la IA estructura las respuestas",
    responses_len_short_title: "Corto",
    responses_len_short_desc: "Ideal para respuestas rápidas, resúmenes y cuando necesitas ahorrar tiempo",
    responses_len_medium_title: "Mediano",
    responses_len_medium_desc: "Respuestas equilibradas con explicaciones adecuadas para la mayoría de las tareas",
    responses_len_auto_title: "Auto",
    responses_len_auto_desc: "La IA determina la mejor longitud según la complejidad de tu pregunta",

    responses_lang_title: "Idioma de Respuesta",
    responses_lang_desc: "Selecciona el idioma para las respuestas de la IA. La configuración se aplica globalmente a todos los proveedores y conversaciones. El soporte de idioma puede variar según el proveedor de LLM seleccionado",
    responses_lang_placeholder: "Selecciona un idioma",

    responses_scroll_title: "Comportamiento de Auto-desplazamiento",
    responses_scroll_desc: "Controla si las respuestas se desplazan automáticamente hacia abajo. Esta configuración se aplica inmediatamente y controla si las respuestas se desplazan automáticamente al contenido más reciente a medida que se transmite",
    responses_scroll_enabled: "Auto-desplazamiento Activado",
    responses_scroll_disabled: "Auto-desplazamiento Desactivado",
    responses_scroll_enabled_desc: "Las respuestas se desplazarán automáticamente hacia abajo a medida que lleguen",
    responses_scroll_disabled_desc: "Las respuestas permanecerán en tu posición de desplazamiento actual",

    responses_memory_title: "Memoria de Conversación",
    responses_memory_desc: "Controla si la IA recuerda discusiones pasadas para mantenerse al tanto del contexto en todos los chats e interacciones de audio.",
    responses_memory_enabled: "Memoria de Conversación Activada",
    responses_memory_disabled: "Memoria de Conversación Desactivada",
    responses_memory_enabled_desc: "La IA recordará detalles de hasta 15 conversaciones pasadas para un contexto global.",
    responses_memory_disabled_desc: "La IA tratará cada conversación como un lienzo completamente limpio.",

    settings_title: "Ajustes del Sistema",
    settings_desc: "Administra tu configuración",

    settings_theme_title: "Personalización del Tema",
    settings_theme_desc: "Personaliza tu experiencia con ajustes de tema y transparencia de ventana",
    settings_theme_license_warning: " (Necesitas una licencia activa para usar esta función)",
    settings_theme_system: "Sistema",
    settings_theme_light: "Modo Claro",
    settings_theme_dark: "Modo Oscuro",
    settings_theme_light_desc: "Usando el tema claro para una mejor visibilidad en entornos brillantes",
    settings_theme_dark_desc: "Usando el tema oscuro para una visualización cómoda con poca luz",
    settings_theme_transparency: "Transparencia de la Ventana",
    settings_theme_transparency_desc: "Ajusta el nivel de transparencia de la ventana de la aplicación",
    settings_theme_transparency_tip: "Consejo: Una mayor transparencia te permite ver a través de la ventana, ideal para superposiciones oscuras. Los cambios se aplican de inmediato.",

    settings_startup_title: "Iniciar con el Sistema",
    settings_startup_desc: "Abrir InvisibleAI automáticamente al iniciar tu sistema",
    settings_startup_label: "Abrir al iniciar",
    settings_startup_enabled: "InvisibleAI se iniciará automáticamente al arrancar el sistema",
    settings_startup_disabled: "InvisibleAI no se iniciará automáticamente",

    settings_icon_title: "Modo Sigilo del Icono",
    settings_icon_desc: "Controla la visibilidad del icono en el dock/barra de tareas cuando la ventana está oculta para la máxima discreción",
    settings_icon_show: "Mostrar icono en Dock/Barra de tareas",
    settings_icon_hide: "Ocultar icono de Dock/Barra de tareas",
    settings_icon_visible_tip: "Activar para hacer visible el icono de la aplicación",
    settings_icon_hidden_tip: "Activar para ocultar el icono de la aplicación",

    settings_always_on_top_title: "Modo Siempre al Frente",
    settings_always_on_top_desc: "Controla si la ventana permanece por encima de todas las demás aplicaciones",
    settings_always_on_top_enabled: "Desactivar Siempre al Frente",
    settings_always_on_top_disabled: "Activar Siempre al Frente",
    settings_always_on_top_enabled_desc: "La ventana permanece por encima de todas las demás aplicaciones (por defecto)",
    settings_always_on_top_disabled_desc: "La ventana se comporta como las aplicaciones normales",

    settings_stealth_title: "Modo Sigilo (Invisible en Capturas)",
    settings_stealth_desc: "Cuando está activado, la app se vuelve invisible en grabaciones de pantalla y capturas. Requiere una licencia activa.",

    settings_reset_title: "Restablecer Ajustes de la Aplicación",
    settings_reset_desc: "Restablece InvisibleAI a sus valores predeterminados de fábrica. Esto eliminará TODOS los datos, incluyendo historial de chat, claves API, licencia, prompts del sistema, ajustes de audio y todas las preferencias. La aplicación se reiniciará automáticamente.",
    settings_reset_warning: "Esta acción es irreversible. Toda tu configuración, claves API, licencia e historial de chat se eliminarán permanentemente.",
    settings_reset_button: "Restablecer Aplicación a Valores de Fábrica",
    settings_reset_button_loading: "Restableciendo...",
    settings_reset_dialog_title: "¿Restablecer todos los datos?",
    settings_reset_dialog_desc: "Esto eliminará permanentemente:",
    settings_reset_dialog_items: "Todos los chats e historial;Claves API;Licencia InvisibleAI y credenciales;Prompts del sistema y preferencias;Ajustes de audio y captura;Tema y ajustes de pantalla;Toda la demás configuración",
    settings_reset_dialog_warn: "La aplicación se reiniciará después de restablecer. Esto no se puede deshacer.",
    settings_reset_dialog_cancel: "Cancelar",
    settings_reset_dialog_confirm: "Restablecer Todo",

    settings_language_title: "Idioma de la App",
    settings_language_desc: "Elige el idioma de visualización para toda la interfaz de la aplicación",
    settings_language_spanish: "Español",
    settings_language_english: "English",
    settings_language_current: "Idioma actual",
    settings_language_active: "Activo",

    api_setup_select_pro: "Seleccionar modelos pro",
    api_setup_license_key: "Clave de Licencia",
    api_setup_license_key_desc: "Después de completar tu compra, recibirás una clave de licencia por correo electrónico. Pégala a continuación para activar.",
    api_setup_license_key_placeholder: "Ingresa tu clave de licencia (ej. 38b1460a-5104-4067-a91d-77b872934d51)",
    api_setup_current_license: "Licencia Actual",
    api_setup_activate: "Activar Licencia",
    api_setup_remove: "Quitar Licencia",
    api_setup_support_info: "Si necesitas ayuda o asistencia, contacta a support@invisibleai.com",
    api_setup_enable_api: "Activar API de InvisibleAI",
    api_setup_disable_api: "Desactivar API de InvisibleAI",
    api_setup_api_enabled_desc: "Usando todas las APIs de InvisibleAI para audio y chat.",
    api_setup_api_disabled_desc: "Usando tus propios proveedores de IA para audio y chat.",
    api_setup_api_no_license_desc: "Se requiere una licencia válida para activar la API de InvisibleAI, o puedes usar tus propios proveedores de IA y STT.",

    audio_title: "Ajustes de Audio",
    audio_desc: "Configura tus dispositivos de entrada y salida de audio para la interacción por voz y captura de audio del sistema.",
    audio_mic_label: "Micrófono",
    audio_mic_desc: "Selecciona tu micrófono para la entrada de voz y dictado. Si ocurren problemas, ajusta el micrófono predeterminado en la configuración del sistema.",
    audio_mic_loading: "Cargando micrófonos...",
    audio_mic_none: "No se encontraron micrófonos",
    audio_mic_placeholder: "Selecciona un micrófono",
    audio_mic_success: "Micrófono cambiado con éxito.",
    audio_mic_refresh_tip: "Haz clic en el botón de actualización para cargar tus micrófonos. Si esto no funciona, intenta cambiar el micrófono predeterminado en los ajustes de tu sistema.",
    audio_mic_tip: "Consejo: Cuando seleccionas un micrófono, la aplicación cambiará a ese dispositivo de inmediato. Puedes verificarlo pasando el cursor sobre el botón del micrófono en la interfaz principal: mostrará el nombre del dispositivo activo.",
    audio_sys_title: "Audio del Sistema",
    audio_sys_desc: "Selecciona el dispositivo de salida para capturar los sonidos del sistema y el audio de las aplicaciones. Si ocurren problemas, establece la salida predeterminada correcta en la configuración del sistema.",
    audio_sys_loading: "Cargando dispositivos de salida...",
    audio_sys_none: "No se encontraron dispositivos de salida",
    audio_sys_placeholder: "Selecciona un dispositivo de salida",
    audio_sys_success: "Dispositivo de salida cambiado con éxito.",
    audio_sys_refresh_tip: "Haz clic en el botón de actualización para cargar los dispositivos de audio del sistema. Si esto no funciona, intenta cambiar la salida de audio predeterminada en los ajustes de tu sistema.",
    audio_sys_tip: "Consejo: La captura de audio del sistema te permite grabar el audio que se reproduce a través de tus altavoces o auriculares. Esto es útil para capturar el audio de una conversación o sonidos del sistema junto con tu voz.",
    audio_trouble_title: "Si los dispositivos seleccionados no funcionan:",
    audio_trouble_desc: "Por favor verifica los ajustes de audio predeterminados de tu sistema. Ve a {mic} para el micrófono y a {audio} para los altavoces/auriculares. Asegúrate de que los dispositivos correctos estén configurados como predeterminados en tu sistema operativo.",
    audio_trouble_note: "Nota: Si el dispositivo seleccionado falla o no está disponible, InvisibleAI recurrirá automáticamente a los dispositivos de audio predeterminados del sistema.",
    audio_default_suffix: " (Predeterminado)",
    audio_refresh_mic_title: "Actualizar lista de micrófonos",
    audio_refresh_sys_title: "Actualizar lista de dispositivos de salida",
    audio_using_prefix: "Usando: ",

    screenshot_title: "Captura de pantalla",
    screenshot_desc: "Administra los ajustes de captura de pantalla",
    screenshot_method_title: "Método de captura",
    screenshot_method_screenshot_desc: "Modo Captura Completa: Captura rápidamente la pantalla completa con un solo clic.",
    screenshot_method_selection_desc: "Modo Selección: Haz clic y arrastra para seleccionar un área específica para capturar.",
    screenshot_method_screenshot_mode: "Modo Captura",
    screenshot_method_selection_mode: "Modo Selección",
    screenshot_method_license_required: "Necesitas una licencia activa para usar el Modo Selección.",
    screenshot_proc_title: "Modo de Procesamiento",
    screenshot_proc_manual_desc: "Las capturas se tomarán y se agregarán automáticamente a tus archivos adjuntos. Luego puedes enviarlas con tu propia consulta. Puedes capturar múltiples pantallas y enviarlas más tarde.",
    screenshot_proc_auto_desc: "Las capturas se enviarán automáticamente a la IA usando tu consulta personalizada. Sin intervención manual. Solo se puede enviar una captura a la vez.",
    screenshot_proc_auto_mode: "Modo Auto",
    screenshot_proc_manual_mode: "Modo Manual",
    screenshot_auto_prompt_label: "Consulta Automática",
    screenshot_auto_prompt_placeholder: "Escribe la consulta para el análisis automático de capturas...",
    screenshot_auto_prompt_help: "Esta consulta se usará automáticamente al tomar capturas de pantalla",
    screenshot_tip: "Consejo: El modo auto es ideal para análisis rápidos, el modo manual te da más control.",

    shortcuts_title: "Cursor y Accesos directos",
    shortcuts_desc: "Administra tu cursor y accesos directos de teclado",
    shortcuts_cursor_title: "Cursor",
    shortcuts_cursor_desc: "Controla la visibilidad del cursor de InvisibleAI",
    shortcuts_cursor_placeholder: "Selecciona un tipo de cursor",
    shortcuts_cursor_invisible: "Invisible",
    shortcuts_cursor_default: "Predeterminado",
    shortcuts_cursor_auto: "Auto",
    shortcuts_cursor_linux_not_supported: "No soportado en Linux",
    shortcuts_kb_title: "Accesos directos de teclado",
    shortcuts_kb_configured: "configurados",
    shortcuts_kb_license_warning: " • Obtén una licencia para personalizar los accesos directos",
    shortcuts_kb_reset_title: "Restablecer todos los accesos directos a los valores predeterminados",
    shortcuts_kb_reset_btn: "Restablecer",
    shortcuts_kb_unlock_title: "Desbloquear personalización de accesos directos",
    shortcuts_kb_unlock_desc: "Puedes activar/desactivar accesos directos, pero necesitas una licencia activa para personalizar las combinaciones de teclas.",
    shortcuts_kb_change_btn: "Cambiar",
    shortcuts_kb_change_btn_title: "Cambiar este acceso directo",
    shortcuts_kb_locked_btn_title: "Se requiere licencia para personalizar",
    shortcuts_kb_footer: "Los accesos directos funcionan globalmente, incluso cuando la aplicación está oculta",

    recorder_waiting: "Esperando teclas...",
    recorder_save: "Guardar",
    recorder_save_title: "Guardar acceso directo",
    recorder_cancel: "Cancelar",
    recorder_cancel_title: "Cancelar",
    recorder_err_arrow: "Las teclas de flecha son automáticas para Mover Ventana. Solo configura modificadores.",
    recorder_err_modifier: "Debe incluir al menos un modificador (Cmd/Ctrl/Alt/Shift)",
    recorder_err_modifier_key: "Debe incluir al menos un modificador (Cmd/Ctrl/Alt/Shift) y una tecla",
    recorder_err_move_modifier: "Mover Ventana necesita al menos un modificador",
    recorder_err_shortcut_modifier: "El acceso directo debe tener al menos un modificador y una tecla",
    recorder_err_invalid: "Combinación de acceso directo no válida",
    recorder_err_not_supported: "Esta combinación de acceso directo no es soportada",
    recorder_err_failed: "Error al validar el acceso directo",
    recorder_help_move: "Presiona teclas modificadoras (ej. Cmd+Shift). Las teclas de flecha funcionan automáticamente.",
    recorder_help_shortcut: "Presiona una combinación de teclas ahora (ej. Cmd+Shift+K)",
    recorder_captured: "Acceso directo capturado. Haz clic en 'Guardar' para aplicar.",

    prompts_title: "Prompts del sistema",
    prompts_desc: "Administra tus perfiles de comportamiento de IA y crea otros nuevos",
    prompts_search_placeholder: "Buscar prompts del sistema...",
    prompts_create_btn: "Crear nuevo",
    prompts_none_title: "No se encontraron prompts",
    prompts_none_desc: "Crea un nuevo prompt para comenzar",
    prompts_edit: "Editar",
    prompts_delete: "Eliminar",
    prompts_default_title: "Prompts predeterminados de InvisibleAI",
    prompts_default_desc: "Prompts preconfigurados con combinaciones óptimas de modelos. Al seleccionar un prompt se configurará automáticamente el modelo de IA recomendado para obtener mejores resultados.",
    prompts_default_loading_title: "Cargando prompts...",
    prompts_default_loading_desc: "Obteniendo prompts predeterminados de InvisibleAI",
    prompts_last_updated: "Última actualización: ",
    prompts_unlock_btn: "Desbloquear",
    prompts_delete_title: "Eliminar Prompt del Sistema",
    prompts_delete_confirm: "¿Estás seguro de que deseas eliminar \"{name}\"?",
    prompts_delete_warning: "Esta acción no se puede deshacer. Esto eliminará permanentemente el prompt del sistema de la base de datos.",
    prompts_deleting: "Eliminando...",
    prompts_create_title: "Crear Prompt del Sistema",
    prompts_edit_title: "Editar Prompt del Sistema",
    prompts_create_desc: "Define un nuevo comportamiento y personalidad de IA.",
    prompts_edit_desc: "Actualiza los detalles de tu prompt del sistema a continuación.",
    prompts_label_name: "Nombre",
    prompts_placeholder_name: "ej. Experto en revisión de código, Escritor creativo...",
    prompts_label_prompt: "Prompt del Sistema",
    prompts_placeholder_prompt: "Eres un asistente de IA servicial. Sé conciso, preciso y amable en tus respuestas...",
    prompts_tip_prompt: "Consejo: Sé específico sobre el tono, nivel de experiencia y formato de respuesta",
    prompts_updating: "Actualizando...",
    prompts_creating: "Creando...",
    prompts_update_btn: "Actualizar",
    prompts_create_btn_save: "Crear",
    prompts_generate_with_ai: "Generar con IA",
    prompts_generate_title: "Generar un prompt del sistema",
    prompts_generate_desc: "Describe el comportamiento de IA que deseas y generaremos un prompt para ti.",
    prompts_generate_placeholder: "ej. Quiero una IA que me ayude con revisiones de código y se enfoque en mejores prácticas...",
    prompts_generate_error_empty: "Por favor describe lo que deseas",
    prompts_generate_error_fail: "Error al generar el prompt",
    prompts_generating: "Generando...",
    prompts_generate_btn: "Generar",
    prompts_license_required: "Necesitas una licencia activa para usar esta función. Haz clic en el botón de abajo para obtener una licencia.",

    chats_title: "Todas las conversaciones",
    chats_desc: "Ver todas tus conversaciones",
    chats_none_title: "No se encontraron conversaciones",
    chats_none_desc: "Inicia una nueva conversación para comenzar",
    chats_search_placeholder: "Buscar conversaciones...",
    chats_messages_count: "mensajes",

    chat_ask_placeholder: "Pregúntame lo que sea...",
    chat_mode_conversation: "Modo Conversación",
    chat_mode_ai_response: "Respuesta de IA",
    chat_scroll_hint: "(Usa las flechas del teclado para desplazarte)",
    chat_toggle_prefix: "Alternar ",
    chat_error_prefix: "Error:",
    chat_generating: "Generando respuesta...",
    chat_role_user: "Tú",
    chat_role_ai: "IA",
    chat_cancel_title: "Cancelar carga",
    chat_close_new_title: "Cerrar e iniciar nueva conversación",
    chat_clear_title: "Limpiar conversación",
  }
};

export type TranslationKey = keyof typeof translations.en;
export type LanguageCode = "en" | "es";

interface LanguageContextType {
  language: string;
  changeLanguage: (lang: string) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [langCode, setLangCode] = useState<LanguageCode>("es");

  useEffect(() => {

    const settings = getResponseSettings();
    const currentLang = settings.language === "english" ? "en" : "es";
    setLangCode(currentLang);

    const handleStorageChange = (e: StorageEvent) => {
      if (e.key === "response_settings") {
        try {
          const parsed = JSON.parse(e.newValue || "{}");
          if (parsed.language) {
            setLangCode(parsed.language === "english" ? "en" : "es");
          }
        } catch {}
      }
    };
    window.addEventListener("storage", handleStorageChange);
    return () => window.removeEventListener("storage", handleStorageChange);
  }, []);

  const changeLanguage = (langId: string) => {

    updateLanguage(langId);
    setLangCode(langId === "english" ? "en" : "es");
  };

  const t = (key: TranslationKey): string => {
    const dict = translations[langCode] || translations.en;
    return dict[key] || translations.en[key] || String(key);
  };

  return (
    <LanguageContext.Provider value={{ language: langCode === "en" ? "english" : "spanish", changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
