import React, { createContext, useContext, useState, useEffect } from "react";

export const translations = {
  en: {

    sidebar_group_core: "Operations",
    sidebar_group_sensors: "Sensors",
    sidebar_group_engine: "Settings & Dev",

    sidebar_dashboard: "Dashboard",
    sidebar_chats: "Chats",
    sidebar_profiles: "AI Profiles",
    profiles_title: "AI Profiles",
    profiles_desc: "Configure modular profile templates, active focus technologies, and session notes to customize AI behavior.",
    profiles_active_title: "Active Configuration",
    profiles_active_fallback: "Default Profile (Legacy System Prompts)",
    profiles_active_fallback_desc: "No modular profile is currently active. The assistant will fall back to your legacy active System Prompt.",
    profiles_templates_title: "Profile Templates",
    profiles_modifiers_title: "Tech Stack & Focus Modifiers",
    profiles_modifiers_desc: "Select optional modifiers to enrich the assistant's context (e.g. programming languages, frameworks, methodologies).",
    profiles_notes_title: "Session Custom Notes",
    profiles_notes_desc: "Temporary instructions, custom rules, or project context appended to the system prompt.",
    profiles_notes_placeholder: "e.g., Working on a refactoring of the auth module, keep security in mind...",
    profiles_save_notes: "Save Session Notes",
    profiles_notes_saved: "Notes saved successfully!",
    profiles_clear_profile: "Deactivate Profile",
    profiles_category_eng: "Engineering",
    profiles_category_data: "Data",
    profiles_category_biz: "Business",
    profiles_category_design: "Design",
    profiles_category_acad: "Academic",
    profiles_category_gen: "General",
    profiles_license_required_title: "Profiles require an active license",
    profiles_license_required_desc: "You can browse the available templates and modifiers, but selecting and customizing a profile is reserved for licensed users.",
    profiles_license_required_badge: "License required",
    profiles_cv_title: "Your CV / Resume",
    profiles_cv_desc: "Upload a PDF, DOCX, TXT or MD résumé — or paste the full text. We parse and store it on this device and feed it to the assistant only while the Interview Expert profile is active.",
    profiles_cv_upload_button: "Upload PDF / DOCX / TXT",
    profiles_cv_paste_placeholder: "Paste your CV here — name, summary, experience, stack, achievements with metrics, languages…",
    profiles_cv_save: "Save CV",
    profiles_cv_clear: "Remove CV",
    profiles_cv_chars: "characters",
    profiles_cv_chars_max: "max",
    profiles_cv_loaded_at: "Last updated",
    profiles_cv_empty: "No CV loaded yet.",
    profiles_cv_format_hint: "Scanned PDF without OCR? Paste the text manually below.",
    profiles_cv_trial_title: "Try the Interview Expert once on the house",
    profiles_cv_trial_desc: "Free accounts get a single trial run of the interview assistant. Once the trial is consumed, the profile and CV editor lock until you activate a license.",
    profiles_cv_trial_used_title: "Free trial already used",
    profiles_cv_trial_used_desc: "You've used your one-time trial. Activate a license to keep coaching interviews with your CV.",
    profiles_cv_only_text: "Supported formats: PDF, DOCX, TXT, MD. Anything else falls back to the paste textarea.",
    sidebar_app_settings: "Settings",
    sidebar_responses: "Responses",
    sidebar_screenshot: "Screenshot",
    sidebar_audio: "Audio",
    sidebar_shortcuts: "Shortcuts",
    sidebar_dev_space: "Dev Space",
    sidebar_support: "Support",
    sidebar_bug: "Report Bug",
    sidebar_quit: "Quit",
    sidebar_version: "Version",
    sidebar_loading: "Loading...",

    enabled: "Enabled",
    disabled: "Disabled",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    loading: "Loading...",
    success: "Success",
    error: "Error",
    warning: "Warning",
    tip: "Tip",
    active: "Active",
    inactive: "Inactive",

    dashboard_title: "Dashboard",
    dashboard_description: "Unlock rapid response generation and premium status options.",
    dashboard_get_license: "Get License",
    dashboard_usage_title: "Activity Stream",
    dashboard_usage_desc: "Monitor live token consumption and runtime sessions.",

    dev_title: "Dev Space",
    dev_desc: "Configure core integrations for primary LLM and transcript interfaces.",
    dev_contribute_title: "Core Contribution Protocol",
    dev_contribute_desc: "Submit fixes to earn lifetime Dev Access. Visit invisibleai.com/contribute.",
    dev_ai_title: "AI Providers",
    dev_ai_desc: "Select your AI provider, API key, and model.",
    dev_stt_title: "STT Providers",
    dev_stt_desc: "Select your speech-to-text provider, API key, and model.",
    dev_locked_licensed_title: "InvisibleAI API active",
    dev_locked_licensed_desc: "You're using the InvisibleAI servers with your license. To configure your own providers and API keys, disable the \"Activate InvisibleAI API\" toggle in the license panel.",
    dev_locked_free_title: "InvisibleAI servers (free mode)",
    dev_locked_free_desc: "You're using the InvisibleAI servers on the free tier. Bring-your-own AI and STT providers are a licensed-only feature.",
    dev_locked_disable_now: "Disable InvisibleAI API now",
    dev_locked_need_license_cta: "Get a license to unlock",
    dev_license_required_title: "License required",
    dev_license_required_ai_desc: "Using your own AI providers (OpenAI, Anthropic, Gemini, custom curl, Ollama …) is reserved for users with an active license. Activate a license to unlock the bring-your-own-provider section.",
    dev_license_required_stt_desc: "Using your own speech-to-text providers (Deepgram, Whisper local, custom STT …) is reserved for users with an active license. Activate a license to unlock the bring-your-own-provider section.",
    dev_license_required_close: "Got it",
    dev_license_required_action: "Activate license",
    dev_select_ai_provider: "Select AI Provider",
    dev_select_ai_provider_desc: "Choose the AI service provider used for responses.",
    dev_select_stt_provider: "Select STT Provider",
    dev_select_stt_provider_desc: "Choose the speech-to-text service provider used for transcription.",
    dev_choose_ai_provider: "Choose your AI provider",
    dev_choose_stt_provider: "Choose your STT provider",
    dev_provider_fallback: "Provider",
    dev_api_key: "API Key",
    dev_api_key_desc: "Enter your {provider} API key. It stays local on this device.",
    dev_submit_api_key: "Submit API Key",
    dev_remove_api_key: "Remove API Key",
    dev_model: "Model",
    dev_model_desc: "Add the model name for {provider}.",
    dev_model_placeholder: "Enter model name",
    dev_advanced_title: "Advanced",
    dev_advanced_ai_desc: "Manage custom AI providers in a separate workspace.",
    dev_advanced_stt_desc: "Manage custom speech-to-text providers in a separate workspace.",
    dev_custom_create: "Custom provider",
    dev_custom_edit: "Edit custom provider",
    dev_custom_empty: "No custom providers configured.",
    dev_custom_no_path: "Response path not set",
    dev_custom_ai_dialog_desc: "Configure a custom AI provider using a cURL template.",
    dev_custom_stt_dialog_desc: "Configure a custom STT provider using a cURL template.",
    dev_custom_curl: "cURL command",
    dev_custom_ai_curl_desc: "Use {{TEXT}}, {{IMAGE}}, {{API_KEY}}, and {{MODEL}} where needed.",
    dev_custom_stt_curl_desc: "Use {{AUDIO}}, {{API_KEY}}, and {{MODEL}} where needed.",
    dev_custom_streaming: "Streaming",
    dev_custom_streaming_desc: "Enable streaming if the provider supports token streaming.",
    dev_custom_response_path: "Path used to extract text from the provider response.",
    dev_custom_delete_title: "Delete custom provider",
    dev_custom_delete_desc: "This custom provider will be removed from local storage.",
    dev_autofill: "Auto-fill",

    responses_title: "Response Settings",
    responses_desc: "Configure AI generation and display style",
    responses_premium_title: "Premium Features",
    responses_premium_desc: "Response customization requires an active license.",

    responses_len_title: "Response Length",
    responses_len_desc: "Choose default response length for new chats.",
    responses_len_short_title: "Short",
    responses_len_short_desc: "Quick, concise answers and summaries.",
    responses_len_medium_title: "Medium",
    responses_len_medium_desc: "Balanced length with standard details.",
    responses_len_auto_title: "Auto",
    responses_len_auto_desc: "AI automatically optimizes response length.",

    responses_lang_title: "Response Language",
    responses_lang_desc: "Select default language for AI responses.",
    responses_lang_placeholder: "Select a language",

    responses_scroll_title: "Auto-Scroll Behavior",
    responses_scroll_desc: "Toggle screen auto-scroll during response generation.",
    responses_scroll_enabled: "Auto-Scroll Enabled",
    responses_scroll_disabled: "Auto-Scroll Disabled",
    responses_scroll_enabled_desc: "Scroll to latest content during streaming.",
    responses_scroll_disabled_desc: "Keep current scroll position.",

    responses_memory_title: "Conversational Memory",
    responses_memory_desc: "Allow AI to recall context from recent chats.",
    responses_memory_enabled: "Conversational Memory Enabled",
    responses_memory_disabled: "Conversational Memory Disabled",
    responses_memory_enabled_desc: "Recalls details from up to 15 past chats.",
    responses_memory_disabled_desc: "Treat each conversation as a clean slate.",

    settings_title: "Settings",
    settings_desc: "Manage your settings",

    settings_theme_title: "Theme Customization",
    settings_theme_desc: "Personalize your experience with custom theme and transparency settings",
    settings_theme_license_warning: " (You need an active license to use this feature)",
    settings_theme_system: "System",
    settings_theme_light: "Light Mode",
    settings_theme_dark: "Dark Mode",
    settings_theme_light_desc: "Using light theme for better visibility in bright environments",
    settings_theme_dark_desc: "Using dark theme for comfortable viewing in low light",
    settings_theme_transparency: "Window Transparency",
    settings_theme_transparency_desc: "Adjust the transparency level of the application window",
    settings_theme_transparency_tip: "Tip: Higher transparency lets you see through the window, perfect for dark overlay. Changes apply immediately.",

    settings_startup_title: "Launch on Startup",
    settings_startup_desc: "Automatically open InvisibleAI when your system starts",
    settings_startup_label: "Open on Start",
    settings_startup_enabled: "InvisibleAI will launch automatically on system startup",
    settings_startup_disabled: "InvisibleAI will not launch automatically",

    settings_icon_title: "App Icon Stealth Mode",
    settings_icon_desc: "Control dock/taskbar icon visibility when window is hidden for maximum discretion",
    settings_icon_show: "Show Icon in Dock/Taskbar",
    settings_icon_hide: "Hide Icon from Dock/Taskbar",
    settings_icon_visible_tip: "Toggle to make App Icon Visible",
    settings_icon_hidden_tip: "Toggle to make App Icon Hidden",

    settings_always_on_top_title: "Always On Top Mode",
    settings_always_on_top_desc: "Control whether the window stays above all other applications",
    settings_always_on_top_enabled: "Disable Always On Top",
    settings_always_on_top_disabled: "Enable Always On Top",
    settings_always_on_top_enabled_desc: "Window stays above all other applications (default)",
    settings_always_on_top_disabled_desc: "Window behaves like normal applications",

    settings_stealth_title: "Stealth Mode (Invisible to Screenshots)",
    settings_stealth_desc: "When enabled, the app becomes invisible to screen recordings and screenshots. Requires an active license.",

    settings_reset_title: "Reset App Configuration",
    settings_reset_desc: "Reset InvisibleAI to its factory defaults. This will delete ALL data including chat history, API keys, license, system prompts, audio settings, and all preferences. The app will restart automatically.",
    settings_reset_warning: "This action is irreversible. All your configuration, API keys, license, and chat history will be permanently deleted.",
    settings_reset_button: "Reset App to Factory Defaults",
    settings_reset_button_loading: "Resetting...",
    settings_reset_dialog_title: "Reset All App Data?",
    settings_reset_dialog_desc: "This will permanently delete:",
    settings_reset_dialog_items: "All chat conversations and history;API keys;InvisibleAI license and credentials;System prompts and preferences;Audio and screenshot settings;Theme and display settings;All other app configuration",
    settings_reset_dialog_warn: "The app will restart after reset. This cannot be undone.",
    settings_reset_dialog_cancel: "Cancel",
    settings_reset_dialog_confirm: "Reset Everything",

    settings_language_title: "App Language",
    settings_language_desc: "Choose the display language for the entire application interface",
    settings_language_spanish: "Español",
    settings_language_english: "English",
    settings_language_current: "Current language",
    settings_language_active: "Active",

    api_setup_select_pro: "Select pro models",
    api_setup_license_key: "License Key",
    api_setup_license_key_desc: "After completing your purchase, you'll receive a license key via email. Paste it below to activate.",
    api_setup_license_key_placeholder: "Enter your license key (e.g., 38b1460a-5104-4067-a91d-77b872934d51)",
    api_setup_current_license: "Current License",
    api_setup_activate: "Activate License",
    api_setup_remove: "Remove License",
    api_setup_support_info: "If you need any help or any assistance, contact support@invisibleai.com",
    api_setup_enable_api: "Enable InvisibleAI API",
    api_setup_disable_api: "Disable InvisibleAI API",
    api_setup_api_enabled_desc: "Using all invisibleai APIs for audio, and chat.",
    api_setup_api_disabled_desc: "Using all your own AI Providers for audio, and chat.",
    api_setup_api_no_license_desc: "A valid license is required to enable InvisibleAI API or you can use your own AI Providers and STT Providers.",

    audio_title: "Audio Settings",
    audio_desc: "Configure your voice input and system audio capture.",
    audio_mic_label: "Microphone",
    audio_mic_desc: "Select microphone for voice input and speech-to-text.",
    audio_mic_loading: "Loading microphones...",
    audio_mic_none: "No microphones found",
    audio_mic_placeholder: "Select a microphone",
    audio_mic_success: "Microphone changed successfully.",
    audio_mic_refresh_tip: "Click refresh to load your microphones.",
    audio_mic_tip: "Microphone updates immediately upon selection.",
    audio_sys_title: "System Audio",
    audio_sys_desc: "Select the output to capture system and app audio.",
    audio_sys_loading: "Loading output devices...",
    audio_sys_none: "No output devices found",
    audio_sys_placeholder: "Select an output device",
    audio_sys_success: "Output device changed successfully.",
    audio_sys_refresh_tip: "Click refresh to load your output devices.",
    audio_sys_tip: "Allows capturing application audio and system sounds.",
    audio_trouble_title: "Check System Settings",
    audio_trouble_desc: "Please verify your default OS audio devices.",
    audio_trouble_note: "Fallback defaults are used if selection fails.",
    audio_default_suffix: " (Default)",
    audio_refresh_mic_title: "Refresh microphones",
    audio_refresh_sys_title: "Refresh output devices",
    audio_using_prefix: "Using: ",

    screenshot_title: "Screenshot",
    screenshot_desc: "Manage your screenshot settings",
    screenshot_method_title: "Capture Method",
    screenshot_method_screenshot_desc: "Screenshot Mode: Quickly capture the entire screen with one click.",
    screenshot_method_selection_desc: "Selection Mode: Click and drag to select a specific area to capture.",
    screenshot_method_screenshot_mode: "Screenshot Mode",
    screenshot_method_selection_mode: "Selection Mode",
    screenshot_method_license_required: "You need an active license to use Selection Mode.",
    screenshot_proc_title: "Processing Mode",
    screenshot_proc_manual_desc: "Screenshots will be captured and automatically added to your attached files. You can then submit them with your own prompt. you can capture multiple screenshots and submit them later.",
    screenshot_proc_auto_desc: "Screenshots will be automatically submitted to AI using your custom prompt. No manual intervention required. only one screenshot can be submitted at a time.",
    screenshot_proc_auto_mode: "Auto Mode",
    screenshot_proc_manual_mode: "Manual Mode",
    screenshot_auto_prompt_label: "Auto Prompt",
    screenshot_auto_prompt_placeholder: "Enter prompt for automatic screenshot analysis...",
    screenshot_auto_prompt_help: "This prompt will be used automatically when screenshots are taken",
    screenshot_tip: "Tip: Auto mode is great for quick analysis, manual mode gives you more control.",

    shortcuts_title: "Cursor & Keyboard Shortcuts",
    shortcuts_desc: "Manage your cursor and keyboard shortcuts",
    shortcuts_cursor_title: "Cursor",
    shortcuts_cursor_desc: "Control invisibleai cursor visibility",
    shortcuts_cursor_placeholder: "Select a cursor type",
    shortcuts_cursor_invisible: "Invisible",
    shortcuts_cursor_default: "Default",
    shortcuts_cursor_auto: "Auto",
    shortcuts_cursor_linux_not_supported: "Not supported on Linux",
    shortcuts_kb_title: "Keyboard Shortcuts",
    shortcuts_kb_configured: "configured",
    shortcuts_kb_license_warning: " • Get a license to customize shortcuts",
    shortcuts_kb_reset_title: "Reset all shortcuts to platform defaults",
    shortcuts_kb_reset_btn: "Reset",
    shortcuts_kb_unlock_title: "Unlock Shortcut Customization",
    shortcuts_kb_unlock_desc: "You can enable/disable shortcuts, but need a active license to customize the key bindings.",
    shortcuts_kb_change_btn: "Change",
    shortcuts_kb_change_btn_title: "Change this shortcut",
    shortcuts_kb_locked_btn_title: "License required to customize",
    shortcuts_kb_footer: "Shortcuts work globally, even when the app is hidden",

    recorder_waiting: "Waiting for keys...",
    recorder_save: "Save",
    recorder_save_title: "Save shortcut",
    recorder_cancel: "Cancel",
    recorder_cancel_title: "Cancel",
    recorder_err_arrow: "Arrow keys are automatic for Move Window. Only set modifiers.",
    recorder_err_modifier: "Must include at least one modifier (Cmd/Ctrl/Alt/Shift)",
    recorder_err_modifier_key: "Must include at least one modifier (Cmd/Ctrl/Alt/Shift) and one key",
    recorder_err_move_modifier: "Move Window needs at least one modifier",
    recorder_err_shortcut_modifier: "Shortcut must have at least one modifier and one key",
    recorder_err_invalid: "Invalid shortcut combination",
    recorder_err_not_supported: "This shortcut combination is not supported",
    recorder_err_failed: "Failed to validate shortcut",
    recorder_help_move: "Press modifier keys (e.g., Cmd+Shift). Arrow keys work automatically.",
    recorder_help_shortcut: "Press a key combination now (e.g., Cmd+Shift+K)",
    recorder_captured: "Shortcut captured. Click 'Save' to apply.",

    chats_title: "All conversations",
    chats_desc: "View all your conversations",
    chats_none_title: "No conversations found",
    chats_none_desc: "Start a new conversation to get started",
    chats_search_placeholder: "Search conversations...",
    chats_messages_count: "messages",

    chat_ask_placeholder: "Ask me anything...",
    chat_mode_conversation: "Conversation Mode",
    chat_mode_ai_response: "AI Response",
    chat_scroll_hint: "(Use arrow keys to scroll)",
    chat_toggle_prefix: "Toggle ",
    chat_error_prefix: "Error:",
    chat_generating: "Generating response...",
    chat_role_user: "You",
    chat_role_ai: "AI",
    chat_cancel_title: "Cancel loading",
    chat_close_new_title: "Close and start new conversation",
    chat_clear_title: "Clear conversation",

    profiles_personality: "Personality:",
    profiles_no_modifiers: "No modifiers available for this profile.",
    profiles_local_changes: "Local changes",
    profiles_saving: "Saving...",

    dashboard_license_title: "License",
    dashboard_license_desc: "Connect your license for premium access. The AI model is configured automatically.",
    dashboard_activate: "Activate",
    dashboard_license_removed: "License removed! You're now on the free tier.",
    dashboard_system_status_title: "System Status",
    dashboard_system_status_licensed_desc: "Full access to all active premium core features.",
    dashboard_system_status_free_desc: "You have access to InvisibleAI servers in free mode. Activate your license for unlimited premium features.",
    dashboard_free_badge: "Free",
    dashboard_credits_title: "Usage Credits",
    dashboard_credits_desc: "Real-time usage — updates after each operation.",
    dashboard_chat_label: "AI Chat",
    dashboard_chat_unit: "tokens today",
    dashboard_stt_label: "Transcriptions (Whisper)",
    dashboard_stt_unit: "calls today (≈15 min free)",
    dashboard_streaming_label: "Streaming Credits",
    dashboard_streaming_available: "available",
    dashboard_streaming_locked_title: "Real-time Streaming",
    dashboard_streaming_locked_desc: "Available on paid plan — activate your license.",

    mem_title: "Contextual Intelligence",
    mem_desc: "Persistent memory, base assistant profile, and error history.",
    mem_categories: "Memory Categories",
    mem_tab_user: "User Memory",
    mem_tab_knowledge: "App Knowledge",
    mem_tab_features: "App Features",
    mem_tab_feedback: "Errors & Feedback",
    mem_filter: "Filter records...",
    mem_add: "Add Record",
    mem_loading: "Loading records...",
    mem_empty: "No records found in this section.",
    mem_priority: "Priority:",
    mem_severity: "Severity:",
    mem_resolved: "Resolved",
    mem_pending: "Pending",
    mem_mark_resolved: "Mark Resolved",
    mem_problem: "Problem:",
    mem_bad_behavior: "Bad behavior:",
    mem_expected_behavior: "Expected behavior:",
    mem_route_info: "Route:",
    mem_modal_add: "Add Record",
    mem_modal_edit: "Edit Record",
    mem_modal_memory_type: "Memory Type",
    mem_modal_memory_content: "Memory Content",
    mem_modal_importance: "Importance (1 - 5)",
    mem_modal_knowledge_title: "Knowledge Title",
    mem_modal_knowledge_category: "Category",
    mem_modal_knowledge_content: "Explanatory content",
    mem_modal_feature_name: "Feature Name",
    mem_modal_feature_desc: "Functional description",
    mem_modal_feature_status: "Status",
    mem_modal_feature_route: "Route / Path (Optional)",
    mem_modal_feature_component: "React Component",
    mem_modal_feature_rust: "Rust Module",
    mem_delete_confirm: "Are you sure you want to delete this record?",
    mem_type_preference: "User Preference",
    mem_type_technical: "Technical Decision / Project",
    mem_type_general: "General Context / Notes",
    mem_category_general: "General / Product",
    mem_category_architecture: "Architecture / Code",
    mem_category_config: "Configuration",
    mem_status_in_dev: "In Development",

    sidebar_voice_agent: "Voice Agent",
    voice_agent_title: "Voice Agent",
    voice_agent_desc: "Real-time conversational AI powered by Deepgram.",
    voice_agent_idle: "Ready",
    voice_agent_connecting: "Connecting...",
    voice_agent_listening: "Listening...",
    voice_agent_thinking: "Thinking...",
    voice_agent_speaking: "Speaking...",
    voice_agent_disconnected: "Disconnected",
    voice_agent_connect: "Start Conversation",
    voice_agent_disconnect: "End Session",
    voice_agent_clear: "Clear",
    voice_agent_transcript: "Conversation",
    voice_agent_license_required_title: "Voice Agent requires a license",
    voice_agent_license_required_desc: "Activate your InvisibleAI license to unlock the real-time voice agent powered by Deepgram.",
    voice_agent_live: "Live session",
    voice_agent_settings_title: "Agent Configuration",
    voice_agent_settings_session_active: "Settings are locked during an active session. End the session to make changes.",
    voice_agent_settings_language: "Language",
    voice_agent_settings_stt_model: "Speech-to-Text Model",
    voice_agent_settings_llm_provider: "LLM Provider",
    voice_agent_settings_llm_model: "LLM Model",
    voice_agent_settings_tts_voice: "Voice",
    voice_agent_settings_greeting: "Greeting Message",
    voice_agent_settings_system_prompt: "System Prompt",
  },
  es: {

    sidebar_group_core: "Operaciones",
    sidebar_group_sensors: "Sensores",
    sidebar_group_engine: "Ajustes y Desarrollo",

    sidebar_dashboard: "Panel",
    sidebar_chats: "Chats",
    sidebar_profiles: "Perfiles de IA",
    profiles_title: "Perfiles de IA",
    profiles_desc: "Configura plantillas de perfiles modulares, enfoques tecnológicos activos y notas de sesión para personalizar la IA.",
    profiles_active_title: "Configuración Activa",
    profiles_active_fallback: "Perfil Predeterminado (System Prompts Legacy)",
    profiles_active_fallback_desc: "No hay un perfil modular activo. El asistente usará tu Prompt de Sistema legacy configurado.",
    profiles_templates_title: "Plantillas de Perfil",
    profiles_modifiers_title: "Modificadores de Enfoque y Tecnologías",
    profiles_modifiers_desc: "Selecciona modificadores opcionales para enriquecer el contexto (ej. lenguajes, frameworks, metodologías).",
    profiles_notes_title: "Notas Personalizadas de Sesión",
    profiles_notes_desc: "Instrucciones temporales, reglas personalizadas o contexto del proyecto que se sumará al prompt.",
    profiles_notes_placeholder: "ej. Trabajando en la refactorización del módulo de autenticación, ten en cuenta la seguridad...",
    profiles_save_notes: "Guardar Notas de Sesión",
    profiles_notes_saved: "¡Notas guardadas con éxito!",
    profiles_clear_profile: "Desactivar Perfil",
    profiles_category_eng: "Ingeniería",
    profiles_category_data: "Datos",
    profiles_category_biz: "Negocios",
    profiles_category_design: "Diseño",
    profiles_category_acad: "Académico",
    profiles_category_gen: "General",
    profiles_license_required_title: "Los perfiles requieren una licencia activa",
    profiles_license_required_desc: "Puedes ver las plantillas y modificadores disponibles, pero seleccionar y personalizar un perfil está reservado para usuarios con licencia.",
    profiles_license_required_badge: "Requiere licencia",
    profiles_cv_title: "Tu CV / Hoja de Vida",
    profiles_cv_desc: "Sube tu CV en PDF, DOCX, TXT o MD — o pega el texto completo. Se procesa y guarda solo en este dispositivo y se inyecta al asistente únicamente cuando el perfil de Entrevistas está activo.",
    profiles_cv_upload_button: "Subir PDF / DOCX / TXT",
    profiles_cv_paste_placeholder: "Pega aquí tu CV — nombre, resumen, experiencia, stack, logros con métricas, idiomas…",
    profiles_cv_save: "Guardar CV",
    profiles_cv_clear: "Quitar CV",
    profiles_cv_chars: "caracteres",
    profiles_cv_chars_max: "máx.",
    profiles_cv_loaded_at: "Última actualización",
    profiles_cv_empty: "Aún no has cargado un CV.",
    profiles_cv_format_hint: "¿PDF escaneado sin OCR? Pega el texto manualmente abajo.",
    profiles_cv_trial_title: "Prueba el Experto en Entrevistas una vez gratis",
    profiles_cv_trial_desc: "Las cuentas free pueden probar el asistente de entrevistas una sola vez. Cuando agotes el ensayo, el perfil y el editor del CV se bloquean hasta que actives una licencia.",
    profiles_cv_trial_used_title: "Prueba gratuita ya utilizada",
    profiles_cv_trial_used_desc: "Ya usaste tu única prueba gratuita. Activa una licencia para seguir entrenando entrevistas con tu CV.",
    profiles_cv_only_text: "Formatos soportados: PDF, DOCX, TXT, MD. Cualquier otro formato se puede pegar como texto en el editor.",
    sidebar_app_settings: "Ajustes",
    sidebar_responses: "Respuestas",
    sidebar_screenshot: "Captura de Pantalla",
    sidebar_audio: "Audio",
    sidebar_shortcuts: "Accesos Directos",
    sidebar_dev_space: "Desarrollo",
    sidebar_support: "Soporte",
    sidebar_bug: "Reportar Bug",
    sidebar_quit: "Salir",
    sidebar_version: "Versión",
    sidebar_loading: "Cargando...",

    enabled: "Activado",
    disabled: "Desactivado",
    cancel: "Cancelar",
    save: "Guardar",
    edit: "Editar",
    delete: "Eliminar",
    loading: "Cargando...",
    success: "Éxito",
    error: "Error",
    warning: "Advertencia",
    tip: "Consejo",
    active: "Activo",
    inactive: "Inactivo",

    dashboard_title: "Panel",
    dashboard_description: "Desbloquea generación rápida de respuestas y estatus premium.",
    dashboard_get_license: "Obtener Licencia",
    dashboard_usage_title: "Flujo de Actividad",
    dashboard_usage_desc: "Monitorea el consumo de tokens y sesiones activas en tiempo real.",

    dev_title: "Espacio de Desarrollo",
    dev_desc: "Configura integraciones de LLM y transcripción.",
    dev_contribute_title: "Protocolo de Contribución",
    dev_contribute_desc: "Corrige problemas críticos para ganar acceso de por vida. Visita invisibleai.com/contribute.",
    dev_ai_title: "Proveedores de IA",
    dev_ai_desc: "Selecciona proveedor de IA, API key y modelo.",
    dev_stt_title: "Proveedores STT",
    dev_stt_desc: "Selecciona proveedor de transcripción, API key y modelo.",
    dev_locked_licensed_title: "API de InvisibleAI activa",
    dev_locked_licensed_desc: "Estás usando los servidores de InvisibleAI con tu licencia. Para configurar tus propios proveedores y API keys, desactiva primero la opción \"Activar API de InvisibleAI\" en el panel de licencia.",
    dev_locked_free_title: "Servidores de InvisibleAI (modo gratuito)",
    dev_locked_free_desc: "Estás conectado a los servidores de InvisibleAI en modo gratuito. Configurar tus propios proveedores de IA y STT es una característica reservada a usuarios con licencia activa.",
    dev_locked_disable_now: "Desactivar API de InvisibleAI ahora",
    dev_locked_need_license_cta: "Obtener licencia para desbloquear",
    dev_license_required_title: "Necesitas una licencia activa",
    dev_license_required_ai_desc: "Usar tus propios proveedores de IA (OpenAI, Anthropic, Gemini, curl personalizado, Ollama…) está reservado para usuarios con licencia activa. Activa una licencia para desbloquear el modo bring-your-own-provider.",
    dev_license_required_stt_desc: "Usar tus propios proveedores de transcripción (Deepgram, Whisper local, STT personalizado…) está reservado para usuarios con licencia activa. Activa una licencia para desbloquear el modo bring-your-own-provider.",
    dev_license_required_close: "Entendido",
    dev_license_required_action: "Activar licencia",
    dev_select_ai_provider: "Seleccionar proveedor de IA",
    dev_select_ai_provider_desc: "Elige el proveedor de IA usado para las respuestas.",
    dev_select_stt_provider: "Seleccionar proveedor STT",
    dev_select_stt_provider_desc: "Elige el proveedor de transcripción usado para convertir audio a texto.",
    dev_choose_ai_provider: "Elige tu proveedor de IA",
    dev_choose_stt_provider: "Elige tu proveedor STT",
    dev_provider_fallback: "Proveedor",
    dev_api_key: "API Key",
    dev_api_key_desc: "Ingresa tu API key de {provider}. Se guarda localmente en este dispositivo.",
    dev_submit_api_key: "Guardar API Key",
    dev_remove_api_key: "Quitar API Key",
    dev_model: "Modelo",
    dev_model_desc: "Agrega el nombre del modelo para {provider}.",
    dev_model_placeholder: "Ingresa el nombre del modelo",
    dev_advanced_title: "Avanzado",
    dev_advanced_ai_desc: "Gestiona proveedores de IA personalizados en un espacio separado.",
    dev_advanced_stt_desc: "Gestiona proveedores STT personalizados en un espacio separado.",
    dev_custom_create: "Proveedor personalizado",
    dev_custom_edit: "Editar proveedor personalizado",
    dev_custom_empty: "No hay proveedores personalizados configurados.",
    dev_custom_no_path: "Ruta de respuesta sin configurar",
    dev_custom_ai_dialog_desc: "Configura un proveedor de IA personalizado usando una plantilla cURL.",
    dev_custom_stt_dialog_desc: "Configura un proveedor STT personalizado usando una plantilla cURL.",
    dev_custom_curl: "Comando cURL",
    dev_custom_ai_curl_desc: "Usa {{TEXT}}, {{IMAGE}}, {{API_KEY}} y {{MODEL}} cuando sea necesario.",
    dev_custom_stt_curl_desc: "Usa {{AUDIO}}, {{API_KEY}} y {{MODEL}} cuando sea necesario.",
    dev_custom_streaming: "Streaming",
    dev_custom_streaming_desc: "Activa streaming si el proveedor soporta transmisión de tokens.",
    dev_custom_response_path: "Ruta usada para extraer el texto de la respuesta del proveedor.",
    dev_custom_delete_title: "Eliminar proveedor personalizado",
    dev_custom_delete_desc: "Este proveedor personalizado se eliminará del almacenamiento local.",
    dev_autofill: "Autocompletar",

    responses_title: "Ajustes de Respuestas",
    responses_desc: "Configura el estilo de generación y visualización de la IA",
    responses_premium_title: "Funciones Premium",
    responses_premium_desc: "La personalización de respuestas requiere una licencia activa.",

    responses_len_title: "Longitud de Respuesta",
    responses_len_desc: "Elige el nivel de detalle para los nuevos chats.",
    responses_len_short_title: "Corto",
    responses_len_short_desc: "Respuestas cortas y resúmenes concisos.",
    responses_len_medium_title: "Mediano",
    responses_len_medium_desc: "Longitud equilibrada con detalles estándar.",
    responses_len_auto_title: "Auto",
    responses_len_auto_desc: "La IA optimiza la longitud automáticamente.",

    responses_lang_title: "Idioma de Respuesta",
    responses_lang_desc: "Selecciona el idioma predeterminado de la IA.",
    responses_lang_placeholder: "Selecciona un idioma",

    responses_scroll_title: "Comportamiento de Auto-desplazamiento",
    responses_scroll_desc: "Controla el desplazamiento automático de pantalla.",
    responses_scroll_enabled: "Auto-desplazamiento Activado",
    responses_scroll_disabled: "Auto-desplazamiento Desactivado",
    responses_scroll_enabled_desc: "Desplazar al contenido más reciente al transmitir.",
    responses_scroll_disabled_desc: "Mantener la posición de lectura actual.",

    responses_memory_title: "Memoria de Conversación",
    responses_memory_desc: "Permite a la IA recordar el contexto de chats recientes.",
    responses_memory_enabled: "Memoria de Conversación Activada",
    responses_memory_disabled: "Memoria de Conversación Desactivada",
    responses_memory_enabled_desc: "Recuerda detalles de hasta 15 chats previos.",
    responses_memory_disabled_desc: "Tratar cada chat como un lienzo limpio.",

    settings_title: "Ajustes del Sistema",
    settings_desc: "Administra tu configuración",

    settings_theme_title: "Personalización del Tema",
    settings_theme_desc: "Personaliza tu experiencia con ajustes de tema y transparencia de ventana",
    settings_theme_license_warning: " (Necesitas una licencia activa para usar esta función)",
    settings_theme_system: "Sistema",
    settings_theme_light: "Modo Claro",
    settings_theme_dark: "Modo Oscuro",
    settings_theme_light_desc: "Usando el tema claro para una mejor visibilidad en entornos brillantes",
    settings_theme_dark_desc: "Usando el tema oscuro para una visualización cómoda con poca luz",
    settings_theme_transparency: "Transparencia de la Ventana",
    settings_theme_transparency_desc: "Ajusta el nivel de transparencia de la ventana de la aplicación",
    settings_theme_transparency_tip: "Consejo: Una mayor transparencia te permite ver a través de la ventana, ideal para superposiciones oscuras. Los cambios se aplican de inmediato.",

    settings_startup_title: "Iniciar con el Sistema",
    settings_startup_desc: "Abrir InvisibleAI automáticamente al iniciar tu sistema",
    settings_startup_label: "Abrir al iniciar",
    settings_startup_enabled: "InvisibleAI se iniciará automáticamente al arrancar el sistema",
    settings_startup_disabled: "InvisibleAI no se iniciará automáticamente",

    settings_icon_title: "Modo Sigilo del Icono",
    settings_icon_desc: "Controla la visibilidad del icono en el dock/barra de tareas cuando la ventana está oculta para la máxima discreción",
    settings_icon_show: "Mostrar icono en Dock/Barra de tareas",
    settings_icon_hide: "Ocultar icono de Dock/Barra de tareas",
    settings_icon_visible_tip: "Activar para hacer visible el icono de la aplicación",
    settings_icon_hidden_tip: "Activar para ocultar el icono de la aplicación",

    settings_always_on_top_title: "Modo Siempre al Frente",
    settings_always_on_top_desc: "Controla si la ventana permanece por encima de todas las demás aplicaciones",
    settings_always_on_top_enabled: "Desactivar Siempre al Frente",
    settings_always_on_top_disabled: "Activar Siempre al Frente",
    settings_always_on_top_enabled_desc: "La ventana permanece por encima de todas las demás aplicaciones (por defecto)",
    settings_always_on_top_disabled_desc: "La ventana se comporta como las aplicaciones normales",

    settings_stealth_title: "Modo Sigilo (Invisible en Capturas)",
    settings_stealth_desc: "Cuando está activado, la app se vuelve invisible en grabaciones de pantalla y capturas. Requiere una licencia activa.",

    settings_reset_title: "Restablecer Ajustes de la Aplicación",
    settings_reset_desc: "Restablece InvisibleAI a sus valores predeterminados de fábrica. Esto eliminará TODOS los datos, incluyendo historial de chat, claves API, licencia, prompts del sistema, ajustes de audio y todas las preferencias. La aplicación se reiniciará automáticamente.",
    settings_reset_warning: "Esta acción es irreversible. Toda tu configuración, claves API, licencia e historial de chat se eliminarán permanentemente.",
    settings_reset_button: "Restablecer Aplicación a Valores de Fábrica",
    settings_reset_button_loading: "Restableciendo...",
    settings_reset_dialog_title: "¿Restablecer todos los datos?",
    settings_reset_dialog_desc: "Esto eliminará permanentemente:",
    settings_reset_dialog_items: "Todos los chats e historial;Claves API;Licencia InvisibleAI y credenciales;Prompts del sistema y preferencias;Ajustes de audio y captura;Tema y ajustes de pantalla;Toda la demás configuración",
    settings_reset_dialog_warn: "La aplicación se reiniciará después de restablecer. Esto no se puede deshacer.",
    settings_reset_dialog_cancel: "Cancelar",
    settings_reset_dialog_confirm: "Restablecer Todo",

    settings_language_title: "Idioma de la App",
    settings_language_desc: "Elige el idioma de visualización para toda la interfaz de la aplicación",
    settings_language_spanish: "Español",
    settings_language_english: "English",
    settings_language_current: "Idioma actual",
    settings_language_active: "Activo",

    api_setup_select_pro: "Seleccionar modelos pro",
    api_setup_license_key: "Clave de Licencia",
    api_setup_license_key_desc: "Después de completar tu compra, recibirás una clave de licencia por correo electrónico. Pégala a continuación para activar.",
    api_setup_license_key_placeholder: "Ingresa tu clave de licencia (ej. 38b1460a-5104-4067-a91d-77b872934d51)",
    api_setup_current_license: "Licencia Actual",
    api_setup_activate: "Activar Licencia",
    api_setup_remove: "Quitar Licencia",
    api_setup_support_info: "Si necesitas ayuda o asistencia, contacta a support@invisibleai.com",
    api_setup_enable_api: "Activar API de InvisibleAI",
    api_setup_disable_api: "Desactivar API de InvisibleAI",
    api_setup_api_enabled_desc: "Usando todas las APIs de InvisibleAI para audio y chat.",
    api_setup_api_disabled_desc: "Usando tus propios proveedores de IA para audio y chat.",
    api_setup_api_no_license_desc: "Se requiere una licencia válida para activar la API de InvisibleAI, o puedes usar tus propios proveedores de IA y STT.",

    audio_title: "Ajustes de Audio",
    audio_desc: "Configura la entrada de voz y captura de audio del sistema.",
    audio_mic_label: "Micrófono",
    audio_mic_desc: "Selecciona el micrófono para entrada de voz y dictado.",
    audio_mic_loading: "Cargando micrófonos...",
    audio_mic_none: "No se encontraron micrófonos",
    audio_mic_placeholder: "Selecciona un micrófono",
    audio_mic_success: "Micrófono cambiado con éxito.",
    audio_mic_refresh_tip: "Haz clic para cargar micrófonos.",
    audio_mic_tip: "El micrófono se actualiza al instante.",
    audio_sys_title: "Audio del Sistema",
    audio_sys_desc: "Selecciona la salida para capturar audio del sistema y apps.",
    audio_sys_loading: "Cargando dispositivos de salida...",
    audio_sys_none: "No se encontraron dispositivos de salida",
    audio_sys_placeholder: "Selecciona un dispositivo de salida",
    audio_sys_success: "Dispositivo de salida cambiado con éxito.",
    audio_sys_refresh_tip: "Haz clic para cargar dispositivos de salida.",
    audio_sys_tip: "Permite grabar el audio del sistema y aplicaciones.",
    audio_trouble_title: "Verifica los Ajustes del Sistema",
    audio_trouble_desc: "Verifica los dispositivos de audio de tu sistema operativo.",
    audio_trouble_note: "Se usarán valores predeterminados si falla la selección.",
    audio_default_suffix: " (Predeterminado)",
    audio_refresh_mic_title: "Actualizar micrófonos",
    audio_refresh_sys_title: "Actualizar dispositivos de salida",
    audio_using_prefix: "Usando: ",

    screenshot_title: "Captura de pantalla",
    screenshot_desc: "Administra los ajustes de captura de pantalla",
    screenshot_method_title: "Método de captura",
    screenshot_method_screenshot_desc: "Modo Captura Completa: Captura rápidamente la pantalla completa con un solo clic.",
    screenshot_method_selection_desc: "Modo Selección: Haz clic y arrastra para seleccionar un área específica para capturar.",
    screenshot_method_screenshot_mode: "Modo Captura",
    screenshot_method_selection_mode: "Modo Selección",
    screenshot_method_license_required: "Necesitas una licencia activa para usar el Modo Selección.",
    screenshot_proc_title: "Modo de Procesamiento",
    screenshot_proc_manual_desc: "Las capturas se tomarán y se agregarán automáticamente a tus archivos adjuntos. Luego puedes enviarlas con tu propia consulta. Puedes capturar múltiples pantallas y enviarlas más tarde.",
    screenshot_proc_auto_desc: "Las capturas se enviarán automáticamente a la IA usando tu consulta personalizada. Sin intervención manual. Solo se puede enviar una captura a la vez.",
    screenshot_proc_auto_mode: "Modo Auto",
    screenshot_proc_manual_mode: "Modo Manual",
    screenshot_auto_prompt_label: "Consulta Automática",
    screenshot_auto_prompt_placeholder: "Escribe la consulta para el análisis automático de capturas...",
    screenshot_auto_prompt_help: "Esta consulta se usará automáticamente al tomar capturas de pantalla",
    screenshot_tip: "Consejo: El modo auto es ideal para análisis rápidos, el modo manual te da más control.",

    shortcuts_title: "Cursor y Accesos directos",
    shortcuts_desc: "Administra tu cursor y accesos directos de teclado",
    shortcuts_cursor_title: "Cursor",
    shortcuts_cursor_desc: "Controla la visibilidad del cursor de InvisibleAI",
    shortcuts_cursor_placeholder: "Selecciona un tipo de cursor",
    shortcuts_cursor_invisible: "Invisible",
    shortcuts_cursor_default: "Predeterminado",
    shortcuts_cursor_auto: "Auto",
    shortcuts_cursor_linux_not_supported: "No soportado en Linux",
    shortcuts_kb_title: "Accesos directos de teclado",
    shortcuts_kb_configured: "configurados",
    shortcuts_kb_license_warning: " • Obtén una licencia para personalizar los accesos directos",
    shortcuts_kb_reset_title: "Restablecer todos los accesos directos a los valores predeterminados",
    shortcuts_kb_reset_btn: "Restablecer",
    shortcuts_kb_unlock_title: "Desbloquear personalización de accesos directos",
    shortcuts_kb_unlock_desc: "Puedes activar/desactivar accesos directos, pero necesitas una licencia activa para personalizar las combinaciones de teclas.",
    shortcuts_kb_change_btn: "Cambiar",
    shortcuts_kb_change_btn_title: "Cambiar este acceso directo",
    shortcuts_kb_locked_btn_title: "Se requiere licencia para personalizar",
    shortcuts_kb_footer: "Los accesos directos funcionan globalmente, incluso cuando la aplicación está oculta",

    recorder_waiting: "Esperando teclas...",
    recorder_save: "Guardar",
    recorder_save_title: "Guardar acceso directo",
    recorder_cancel: "Cancelar",
    recorder_cancel_title: "Cancelar",
    recorder_err_arrow: "Las teclas de flecha son automáticas para Mover Ventana. Solo configura modificadores.",
    recorder_err_modifier: "Debe incluir al menos un modificador (Cmd/Ctrl/Alt/Shift)",
    recorder_err_modifier_key: "Debe incluir al menos un modificador (Cmd/Ctrl/Alt/Shift) y una tecla",
    recorder_err_move_modifier: "Mover Ventana necesita al menos un modificador",
    recorder_err_shortcut_modifier: "El acceso directo debe tener al menos un modificador y una tecla",
    recorder_err_invalid: "Combinación de acceso directo no válida",
    recorder_err_not_supported: "Esta combinación de acceso directo no es soportada",
    recorder_err_failed: "Error al validar el acceso directo",
    recorder_help_move: "Presiona teclas modificadoras (ej. Cmd+Shift). Las teclas de flecha funcionan automáticamente.",
    recorder_help_shortcut: "Presiona una combinación de teclas ahora (ej. Cmd+Shift+K)",
    recorder_captured: "Acceso directo capturado. Haz clic en 'Guardar' para aplicar.",

    chats_title: "Todas las conversaciones",
    chats_desc: "Ver todas tus conversaciones",
    chats_none_title: "No se encontraron conversaciones",
    chats_none_desc: "Inicia una nueva conversación para comenzar",
    chats_search_placeholder: "Buscar conversaciones...",
    chats_messages_count: "mensajes",

    chat_ask_placeholder: "Pregúntame lo que sea...",
    chat_mode_conversation: "Modo Conversación",
    chat_mode_ai_response: "Respuesta de IA",
    chat_scroll_hint: "(Usa las flechas del teclado para desplazarte)",
    chat_toggle_prefix: "Alternar ",
    chat_error_prefix: "Error:",
    chat_generating: "Generando respuesta...",
    chat_role_user: "Tú",
    chat_role_ai: "IA",
    chat_cancel_title: "Cancelar carga",
    chat_close_new_title: "Cerrar e iniciar nueva conversación",
    chat_clear_title: "Limpiar conversación",

    profiles_personality: "Personalidad:",
    profiles_no_modifiers: "No hay modificadores disponibles para este perfil.",
    profiles_local_changes: "Cambios locales",
    profiles_saving: "Guardando...",

    dashboard_license_title: "Licencia",
    dashboard_license_desc: "Conecta tu licencia para acceso premium. El modelo de IA se configura automáticamente.",
    dashboard_activate: "Activar",
    dashboard_license_removed: "¡Licencia eliminada! Continúas en modo gratuito.",
    dashboard_system_status_title: "Estado del Sistema",
    dashboard_system_status_licensed_desc: "Tienes acceso completo a todas las funciones premium activas.",
    dashboard_system_status_free_desc: "Accedes a los servidores de InvisibleAI en modo gratuito. Activa tu licencia para funciones premium sin límites.",
    dashboard_free_badge: "Gratuito",
    dashboard_credits_title: "Balance de Créditos",
    dashboard_credits_desc: "Consumo en tiempo real — se actualiza tras cada operación.",
    dashboard_chat_label: "Chat IA",
    dashboard_chat_unit: "tokens hoy",
    dashboard_stt_label: "Transcripciones (Whisper)",
    dashboard_stt_unit: "llamadas hoy (≈15 min gratis)",
    dashboard_streaming_label: "Créditos Streaming",
    dashboard_streaming_available: "disponibles",
    dashboard_streaming_locked_title: "Streaming en tiempo real",
    dashboard_streaming_locked_desc: "Disponible en plan de pago — activa tu licencia.",

    mem_title: "Inteligencia Contextual",
    mem_desc: "Memoria persistente, perfil base de asistente e historial de errores.",
    mem_categories: "Categorías de Memoria",
    mem_tab_user: "Memoria del Usuario",
    mem_tab_knowledge: "Conocimiento de la App",
    mem_tab_features: "Funciones de la App",
    mem_tab_feedback: "Errores y Feedback",
    mem_filter: "Filtrar registros...",
    mem_add: "Añadir Registro",
    mem_loading: "Cargando registros...",
    mem_empty: "No se encontraron registros en esta sección.",
    mem_priority: "Prioridad:",
    mem_severity: "Severidad:",
    mem_resolved: "Resuelto",
    mem_pending: "Pendiente",
    mem_mark_resolved: "Marcar Resuelto",
    mem_problem: "Problema:",
    mem_bad_behavior: "Mal comportamiento:",
    mem_expected_behavior: "Comportamiento esperado:",
    mem_route_info: "Ruta:",
    mem_modal_add: "Añadir Registro",
    mem_modal_edit: "Editar Registro",
    mem_modal_memory_type: "Tipo de Memoria",
    mem_modal_memory_content: "Contenido de la Memoria",
    mem_modal_importance: "Importancia (1 - 5)",
    mem_modal_knowledge_title: "Título del Conocimiento",
    mem_modal_knowledge_category: "Categoría",
    mem_modal_knowledge_content: "Contenido explicativo",
    mem_modal_feature_name: "Nombre de la Característica",
    mem_modal_feature_desc: "Descripción funcional",
    mem_modal_feature_status: "Estado",
    mem_modal_feature_route: "Ruta / Path (Opcional)",
    mem_modal_feature_component: "Componente React",
    mem_modal_feature_rust: "Módulo Rust",
    mem_delete_confirm: "¿Estás seguro de que deseas eliminar este registro?",
    mem_type_preference: "Preferencia de Usuario",
    mem_type_technical: "Decisión Técnica / Proyecto",
    mem_type_general: "Contexto General / Notas",
    mem_category_general: "General / Producto",
    mem_category_architecture: "Arquitectura / Código",
    mem_category_config: "Configuración",
    mem_status_in_dev: "En desarrollo",

    sidebar_voice_agent: "Agente de Voz",
    voice_agent_title: "Agente de Voz",
    voice_agent_desc: "IA conversacional en tiempo real impulsada por Deepgram.",
    voice_agent_idle: "Listo",
    voice_agent_connecting: "Conectando...",
    voice_agent_listening: "Escuchando...",
    voice_agent_thinking: "Pensando...",
    voice_agent_speaking: "Hablando...",
    voice_agent_disconnected: "Desconectado",
    voice_agent_connect: "Iniciar conversación",
    voice_agent_disconnect: "Finalizar sesión",
    voice_agent_clear: "Limpiar",
    voice_agent_transcript: "Conversación",
    voice_agent_license_required_title: "El agente de voz requiere una licencia",
    voice_agent_license_required_desc: "Activa tu licencia de InvisibleAI para desbloquear el agente de voz en tiempo real impulsado por Deepgram.",
    voice_agent_live: "Sesión activa",
    voice_agent_settings_title: "Configuración del Agente",
    voice_agent_settings_session_active: "La configuración está bloqueada durante una sesión activa. Finalizá la sesión para hacer cambios.",
    voice_agent_settings_language: "Idioma",
    voice_agent_settings_stt_model: "Modelo de transcripción",
    voice_agent_settings_llm_provider: "Proveedor LLM",
    voice_agent_settings_llm_model: "Modelo LLM",
    voice_agent_settings_tts_voice: "Voz",
    voice_agent_settings_greeting: "Mensaje de bienvenida",
    voice_agent_settings_system_prompt: "Prompt del sistema",
  }
};

export type TranslationKey = keyof typeof translations.en;
export type LanguageCode = "en" | "es";

interface LanguageContextType {
  language: string;
  changeLanguage: (lang: string) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [langCode, setLangCode] = useState<LanguageCode>("en");

  useEffect(() => {
    const saved = localStorage.getItem("app_language") || "en";
    setLangCode(saved === "es" ? "es" : "en");

    const handleStorageChange = (e: StorageEvent) => {
      if (e.key === "app_language") {
        const val = e.newValue || "en";
        setLangCode(val === "es" ? "es" : "en");
      }
    };
    window.addEventListener("storage", handleStorageChange);
    return () => window.removeEventListener("storage", handleStorageChange);
  }, []);

  const changeLanguage = (langId: string) => {
    const code = langId === "english" ? "en" : "es";
    localStorage.setItem("app_language", code);
    setLangCode(code);
  };

  const t = (key: TranslationKey): string => {
    const dict = translations[langCode] || translations.en;
    return dict[key] || translations.en[key] || String(key);
  };

  return (
    <LanguageContext.Provider value={{ language: langCode === "en" ? "english" : "spanish", changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
